<?php
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$colClass = $themeHelper->getColClass();
$arrColClass = explode(' ', $colClass);
$pageType = 'catalog';
$settings = $themeHelper->getThemeSettings();
$perrow = $settings['catalog']['per_row'];
if($this->hasData('page_type')){
	$pageType = $this->getData('page_type');
}
if($pageType == 'catalog'){
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
	if($category->getPerRow()){
		$perrow = $category->getPerRow();
	}
}elseif($pageType == 'catalogsearch') {
	if($settings['catalogsearch']['per_row']){
		$perrow = $settings['catalogsearch']['per_row'];
	}
}
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>" id="product-wrapper">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items row <?php echo 'row-'.$arrColClass[0] ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			<?php $params = $block->getRequest()->getParams();  ?>
			<?php if($themeSettings['catalog']['ajaxscroll']){
				if(isset($params['product_list_limit'])){
					$countAll = $params['product_list_limit'];
				}else{
					$countAll = $themeHelper->getStoreConfig('catalog/frontend/grid_per_page');			
				}
				if(isset($params['p'])){
					$i = ($params['p'] - 1) * $countAll;
				}else {
					$i = 0;
				}
			}else {
				$i = 0;
			}
			?>
            <?php foreach ($_productCollection as $_product): $i++; ?>
				<?php if ($block->getMode() == 'grid'):?>
					<?php echo($iterator++ == 1) ? '<li class="item product product-item '. $colClass .' '. $themeHelper->getClearClass($perrow, $i).'">' : '</li><li class="item product product-item '. $colClass .' '. $themeHelper->getClearClass($perrow, $i).'">' ?>
				<?php else:?>
					<?php echo($iterator++ == 1) ? '<li class="item product product-item col-md-12 col-sm-12 col-xs-12">' : '</li><li class="item product product-item col-md-12 col-sm-12 col-xs-12">' ?>
				<?php endif;?>
				<?php
					$_productNameStripped = $block->stripTags($_product->getName(), null, true);
				?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
					$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
					$size = $themeHelper->getImageSize();
                    $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
					//$block->getImage($_product, $image);
                    
                    ?>
					<?php if ($block->getMode() == 'grid'):?>
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
							</a>
							<?php echo $themeHelper->getProductLabel($_product) ?>
							<ul class="actions-link" data-role="add-to-links">
								<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
										<li><a href="#"
											data-title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   class="action towishlist btn btn-default"
										   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
										   data-action="add-to-wishlist"
										   role="button">
											<i class="fa fa-heart"></i>
										</a></li>
									<?php endif; ?>
									<?php
									$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
									?>
									<?php if(!$themeSettings['catalog']['compare_button']): ?>
										<li><a href="#"
											data-title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   class="action tocompare btn btn-default"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<i class="fa fa-random"></i>
										</a></li>
									<?php endif ?>
								<?php endif ?>
								
								<?php /* Append Quick View */ ?>
								<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
								<li class="hidden-sm hidden-xs"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></li>
							</ul>
						</div>
						<div class="product details product-item-details">
							<h5 class="product name product-item-name">
								<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</h5>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
							<?php echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>
							<div class="product-item-inner">
								<div class="product actions product-item-actions">
									<div class="actions-primary">
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="btn btn-primary action tocart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
					<?php else: ?>
						<?php // Product Image ?>
						<div class="row margin-bottom30">
							<div class="col-md-4 col-sm-3 col-xs-12">
								<div class="product-image-content">
									<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
										<?php echo $themeHelper->getProductLabel($_product) ?>
									</a>
									<?php /* Append Quick View */ ?>
									<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
									<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
								</div>
							</div>
							<div class="col-md-8 col-sm-9 col-xs-12">
								<div class="product details product-item-details">
									
									<strong class="product name product-item-name">
										<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>">
											<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
										</a>
									</strong>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									<?php echo $block->getProductPrice($_product) ?>
									<?php echo $block->getProductDetailsHtml($_product); ?>

									<div class="product-item-inner">
										<div class="product actions product-item-actions">
											<div class="actions-primary">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
																class="btn btn-primary action tocart">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													</form>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
											<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
												<div data-role="add-to-links" class="actions-secondary">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
														<a href="#"
														   class="action towishlist btn btn-default"
														   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
														   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
														   data-action="add-to-wishlist"
														   role="button">
															<i class="fa fa-heart"></i>
														</a>
													<?php endif; ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<?php if(!$themeSettings['catalog']['compare_button']): ?>
														<a href="#"
														   class="action tocompare btn btn-default"
														   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
														   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
														   role="button">
															<i class="fa fa-random"></i>
														</a>
													<?php endif ?>
												</div>
											<?php endif ?>
										</div>
										<?php if ($showDescription):?>
											<div class="product description product-item-description">
												<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
												   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
											</div>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
					<?php endif ?>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
	<div class="bottom-pagination">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
