<?php $images = json_decode($this->getWidgetInstagramData()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block instagram-block">
	<?php if($this->hasData('mgs_panel_title') || $this->hasData('mgs_panel_note')): ?>
		<div class="content-heading">
			<?php if($this->hasData('mgs_panel_title')): ?>
				<h2 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h2>
			<?php endif ?>
			<?php if($this->hasData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if(count($images)>0): ?>
		<?php 
			$blockId = rand() . time();
			$useSlider = $this->getUseSlider();
			$perRow = $this->getPerrow(); 
			if($useSlider && $this->hasData('number_row') && $this->getNumberRow()>1){
				$columnCount = $perRow * $this->getNumberRow();
			}
			$col = $themeHelper->convertPerRowtoCol($perRow);
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		<?php if($useSlider): ?>
			<div class="row">
				<div id="instagram-widget<?php echo $blockId ?>" class="owl-carousel">
					<?php $i=0; $j=0; foreach($images as $image): $i++; ?>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							<?php if ($j++ % $columnCount == 0): ?>
								<div class="item">
							<?php endif ?>
						<?php endif ?>
						
						<div<?php if($this->getNumberRow()>1): ?> class="<?php echo $themeHelper->getClearClass($perRow, $i) ?> <?php echo $themeHelper->convertColClass($col, 'col') ?>"<?php else: ?>  class="instagram-item"<?php endif ?>>
							<?php if($this->getLink()): ?>
								<a href="<?php echo $image->permalink ?>" target="_blank">
							<?php endif ?>
							
								<img class="img-responsive" src="<?php echo $image->media_url ?>" alt=""/>
							
							<?php if($this->getLink()): ?>
								</a>
							<?php endif ?>
						</div>
						<?php if($this->hasData('number_row') && $this->getNumberRow()>1): ?>
							<?php if ($j % $columnCount == 0 || $j == count($images)): ?>
								</div>
							<?php endif ?>
						<?php endif ?>
					<?php endforeach ?>
				</div>
				<?php if($this->hasData('number_row') && $this->getNumberRow()>1):?>
					<?php $perRow = 1; ?>
				<?php endif ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						var owlinstagram<?php echo $blockId ?> = $('#instagram-widget<?php echo $blockId ?>').owlCarousel({
							items: <?php echo $perRow; ?>,
							autoplay: <?php echo $autoPlay ?>,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
							navText: ["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"],
							<?php if(!$this->hasData('number_row') || $this->getNumberRow()==1):?>
								responsive:{
									0:{
										items:2
									},
									480:{
										items:2
									},
									992:{
										items:<?php echo $perRow; ?>
									}
								}
							<?php endif ?>
						});
					});
				</script>
			</div>
		<?php else: ?>
			<div class="block-content">
				<ul class="row">
					<?php foreach($images as $image): ?>
						<li class="col-md-<?php echo $col ?> col-sm-4 col-xs-6">
							<div class="instagram-item">
								<?php if($this->getLink()): ?>
									<a href="<?php echo $image->permalink ?>" target="_blank">
								<?php endif ?>
								
									<img class="img-responsive" src="<?php echo $image->media_url ?>" alt=""/>
								
								<?php if($this->getLink()): ?>
									</a>
								<?php endif ?>
								
								
							</div>
						</li>
					<?php endforeach ?>
				</ul>
			</div>
		<?php endif ?>

	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('Can not get Instagram data or your instagram account have not any images.') ?></div>
	<?php endif ?>
</div>