<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \Aheadworks\Layerednav\Block\Navigation */

// @codingStandardsIgnoreFile
?>
<div id="layered-filter-block"
     class="block filter aw-layered-nav"
     data-role="filter-block"
     data-mage-init='{"collapsible":{
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral": {
                "openedState": "filter-active",
                "element": "body"
            }
         }}'>
    <div class="block-title filter-title">
        <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
    </div>
    <div id="aw-layered-nav-popup"
         class="aw-layered-nav-popover aw-layered-nav-popover" style="display:none"
         data-role="aw-layered-nav-popover"
         data-mage-init='{"awLayeredNavPopover": {
                "filtersContainer": "#layered-filter-block",
                "isPopoverDisabled": <?php /* @noEscape */ echo \Zend_Json::encode($block->isPopoverDisabled()) ?>,
                "hasActiveFilters": <?php /* @noEscape */ echo \Zend_Json::encode($block->hasActiveFilters()) ?>}}'>
        <div class="aw-layered-nav-popover__content">
            <div id="aw-layered-nav-popover__items" data-role="items-count-container" class="aw-layered-nav-popover__items"></div>
            <div class="aw-layered-nav-popover__loader"><div class="aw-layered-nav-popover__loader-itself"></div></div>
            <div class="aw-layered-nav-popover__action">
                <button data-role="show-button" class="action primary btn btn-default btn-sm show-button"><span><?php /* @escapeNotVerified */ echo __('Show');?></span></button>
            </div>
        </div>
    </div>
    <div class="block-content filter-content">
		<h3 class="close-filter-fixed">
			<?php echo __('Filter'); ?>
		</h3>
		<div class="block-filter-content">
			<strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Shopping Options') ?></strong>
			<div class="filter-options" id="narrow-by-list">
				<?php foreach ($block->getFilters() as $filter): ?>
					<?php if ($block->canShowFilter($filter)): ?>
						<div class="filter-options-item<?php if ($block->isFilterExpanded($filter)): ?> active<?php endif; ?>"
							 id="aw-filter-<?php /* @noEscape */ echo $filter->getRequestVar(); ?>"
							 data-mage-init='{"awLayeredNavCollapse": {}}'>
							<div data-role="title" class="filter-options-title">
								<span class="label"><?php echo $block->escapeHtml(__($filter->getName())) ?></span>
								<span class="arrow"></span>
								<span class="reset<?php if (!$block->isFilterActive($filter)): ?> disabled<?php endif; ?>"
									  data-mage-init='{"awLayeredNavFilterReset": {"params":["<?php /* @noEscape */ echo $filter->getRequestVar(); ?>"]}}'>
								</span>
							</div>
							<div data-role="content" class="filter-options-content"><?php /* @noEscape */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
						</div>
					<?php endif; ?>
				<?php endforeach; ?>
				<div class="button-list aw-layered-nav-popover__action"
					 data-role="aw-layered-nav-actions"
					 data-mage-init='{"awLayeredNavFilterActions": {}}'>
					<button data-role="clear-button" class="action primary clear-button btn btn-default btn-sm" <?php if (!$block->hasActiveFilters()): ?> disabled<?php endif; ?>>
						<span><?php /* @escapeNotVerified */ echo __('Clear All');?></span>
					</button>
					<?php if (!$block->isPopoverDisabled()): ?>
					<button data-role="show-button" class="action primary btn btn-default btn-sm show-button<?php if (!$block->hasActiveFilters()): ?> disabled<?php endif; ?>"><span><?php /* @escapeNotVerified */ echo __('Show');?></span></button>
					<?php endif; ?>
				</div>
			</div>
		</div>
    </div>
</div>

<script>
    require([
        'jquery',
        'Aheadworks_Layerednav/js/filter/request/bridge',
    <?php if ($block->isAjaxEnabled()): ?>
        'Aheadworks_Layerednav/js/filter/request/executor/ajax',
    <?php else: ?>
        'Aheadworks_Layerednav/js/filter/request/executor/location',
    <?php endif; ?>
        'Aheadworks_Layerednav/js/url/processor/bridge',
    <?php if ($block->isUseAttrValueInsteadOfId()): ?>
        'Aheadworks_Layerednav/js/url/processor/processor/value-instead-of-id',
    <?php elseif ($block->isUseSubcategoriesAsAttrValues()): ?>
        'Aheadworks_Layerednav/js/url/processor/processor/value-as-subcategory',
    <?php else: ?>
        'Aheadworks_Layerednav/js/url/processor/processor/default',
    <?php endif; ?>
        'Aheadworks_Layerednav/js/filter/data/source/ajax',
        'Aheadworks_Layerednav/js/product-list/pager'
    ], function (
        $,
        requestBridge,
        executor,
        urlProcessorBridge,
        urlProcessor,
        ajaxDataSource,
    ) {
        requestBridge.init({executor: executor});
        urlProcessorBridge.init({processor: urlProcessor});
        ajaxDataSource.init(<?php /* @noEscape */ echo \Zend_Json::encode($block->getDataSourceConfig()) ?>);
        $('.pages').awLayeredNavPager({});
    });
</script>
