<?php $block = $this->getBlock() ?>

<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>

<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php $customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
<?php $customerUrl = $objectManager->create('Magento\Customer\Model\Url'); ?>

<?php $topLeftBlock = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_8_top_left_link')->setCanUsePanel($canUsePanel)->toHtml(); ?>

<div class="top-header-content">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-xs-12">
				<!-- Static block: header_8_top_left_link -->
				<?php if($topLeftBlock): ?>
					<div class="top-custom-link">
						<?php echo $topLeftBlock; ?>
					</div>
				<?php endif ?>
			</div>
			<div class="col-md-4 hidden-sm hidden-xs col-xs-12">
				<?php echo $block->getChildHtml('store_language') ?>
				<?php echo $block->getChildHtml('currency') ?>
			</div>
		</div>
	</div>
</div>
<div class="middle-header-content">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-xs-6 logo-header">
				<?php echo $block->getChildHtml('logo') ?>
			</div>
			<div class="col-lg-9 col-md-9 col-xs-6 parent__megameu">
				<div class="megamenu-content<?php if($block->getChildHtml('store.settings') == ""): ?> no-menu-settings<?php endif ?>">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#main-Menucontent"><?php echo __('Menu'); ?></a></li>
						<li><a data-toggle="tab" href="#main-Accountcontent"><?php echo __('Account'); ?></a></li>
						<li class="settings-menu-tab"><a data-toggle="tab" href="#main-Settingcontent"><?php echo __('Setting'); ?></a></li>
					</ul>
					<div class="tab-content">
						<div id="main-Menucontent" class="tab-pane active">
							<?php if($block->getChildHtml('megamenu')!=''): ?>
								<?php echo $block->getChildHtml('megamenu') ?>
							<?php else: ?>
								<?php echo $block->getChildHtml('catalog.topnav') ?>
							<?php endif ?>
						</div>
						<div id="main-Accountcontent" class="tab-pane">
							<div class="top-links">
								<?php echo $block->getChildHtml('top.links') ?>
							</div>
						</div>
						<div id="main-Settingcontent" class="tab-pane">
							<?php echo $block->getChildHtml('store.settings') ?>
						</div>
						
					</div>
				</div>
				<div class="text-right hidden-lg">
					<button class="action nav-toggle hidden-lg">
						<img src="<?php echo $block->getViewFileUrl('images/hamburger-black.svg'); ?>" alt="<?php echo __('Toogle Menu') ?>">
					</button>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="bottom-header-content">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-xs-12">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('claue_vertical_menu_header')->setCanUsePanel($canUsePanel)->toHtml(); ?>
			</div>
			<div class="col-lg-9 col-md-9 col-xs-12">
				<div class="parent__search">
					<?php echo $block->getChildHtml('top.search') ?>
					<div class="table-icon-menu">
						<div class="dropdown dropdown-toplinks">
							<button class="dropdown-toggle" type="button" data-toggle="dropdown"><i class="pe-7s-user"></i></button>
							<div class="dropdown-menu">
								<?php echo $block->getChildHtml('top.links') ?>
							</div>
						</div>
						
						<?php if($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
							<div class="header-wl" data-bind="scope: 'wishlist'">
								<a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Wishlist\Helper\Data')->getListUrl() ?>">
									<i class="pe-7s-like"></i>
									<?php if($this->helper('Magento\Wishlist\Helper\Data')->getItemCount() > 0): ?>
										<span class="count-wl"><?php echo $this->helper('Magento\Wishlist\Helper\Data')->getItemCount(); ?></span>
									<?php endif ?>
								</a>
							</div>
						<?php endif ?>
						
						<div class="search-form select-search">
							<div class="actions-search visible-sm visible-xs">
								<button class="action-search" onclick="showHideFormSearch()"><i class="pe-7s-search"></i></button>
							</div>
						</div>
						
						<?php echo $block->getChildHtml('minicart') ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<button class="action close-nav-button"><span class="pe-7s-close" aria-hidden="true"></span></button>