<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$helper =  $this->helper('MGS\Mpanel\Helper\Data');
?>
<script>
	var BASE_URL = WEB_URL = '<?= $block->escapeUrl($block->getBaseUrl()) ?>';
	var RTL = true;
    var require = {
        "baseUrl": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('/') ?>"
    };
    <?php if($helper->getFullActionName() == 'catalog_category_view'): ?>
    var CATALOG_CHECK = 1;
    <?php else: ?>
    var CATALOG_CHECK = 0;
    <?php endif ?>
    <?php if($helper->getFullActionName() == 'catalog_product_view' || $helper->getFullActionName() == 'mgs_quickview_catalog_product_view'): ?>
    var CATALOG_CHECK = 2;
    <?php endif ?>
</script>
