<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $filters = $block->getActiveFilters() ?>
<?php if (!empty($filters)): ?>
<div class="filter-current">
    <strong class="block-subtitle filter-current-subtitle"><?php echo __('Now Shopping by') ?></strong>
	<?php $filtersId = array(); ?>
	<?php foreach ($filters as $_filter): ?>
		<?php if(!in_array($_filter->getValue(), $filtersId)): ?>
			<?php 
				$filtersId[] = $_filter->getValue(); 
				$currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
			?>
			<span class="shoppingby-item">
				<span class="state-item">
					<a class="action remove" href="<?= $_filter->getRemoveUrl() ?>" title="<?= $block->escapeHtml(__('Remove')) . " " . $block->escapeHtml($currentFilterName);?>">
						<span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?></span>
						<span class="filter-value"><?php echo $block->stripTags($_filter->getLabel()) ?></span>
					</a>
				</span>
			</span>
		<?php endif; ?>
	<?php endforeach; ?>
	<a href="<?= $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= __('Clear All') ?></span></a>
</div>
<?php endif; ?>
