<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php if ($block->canShowBlock()): ?>
    <amp-sidebar id="catalog_filter" class="block filter left-sidebar" side="left" layout="nodisplay">
		<?= $block->getChildHtml('ampstate'); ?>
        <div class="block-title filter-title hide">
            <strong><?php echo __('Shop By') ?></strong>
			<button class="close-filter" on="tap:catalog_filter.close"></button>
        </div>
        <div class="block-content filter-content">
            <ul class="filter-options">
                <?php foreach ($block->getFilters() as $key => $filter): ?>
                    <?php if ($filter->getItemsCount()): ?>
						<?php $attributeModel = $filter->getAttributeModel(); ?>
						<li>
							<label for="filter-item-<?php echo $key ?>" class="filter-options-title">
								<?php echo $block->escapeHtml(__('Filter by %1',$filter->getName())) ?>
							</label>
							<?php echo $block->getChildBlock('render')->render($filter); ?>
						</li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </amp-sidebar>
<?php endif; ?>
