<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $helper = $this->helper('MGS\Protabs\Helper\Data') ?>
<?php $tabCollection = $helper->getTabsCollection() ?>
<?php $_ampHelper = $this->helper('MGS\Amp\Helper\Config'); ?>
<?php if(count($tabCollection)): ?>
	<div class="product info detailed">
		<?php $layout = $block->getLayout(); ?>
		<amp-accordion disable-session-states animate class="product-tabs">
			<?php foreach($tabCollection as $_tab): ?>
				<?php if(($_tab->getTabType() == 'attribute') || ($_tab->getTabType() == 'static')): ?>
					<?php if(trim($_tab->getValue()) !=''): ?>
						<?php if($_tab->getTabType() == 'attribute'): ?>
							<?php 
								$html = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Description')
								->setAtCall($helper->convertAttributeToCallName($_tab->getValue()))
								->setAtCode($_tab->getValue())
								->setCssClass('description')
								->setAtLabel('none')
								->setAtType($helper->getAttributeType($_tab->getValue()))
								->setTitle($_tab->getTitle())
								->setTemplate('MGS_Protabs::product/view/attribute.phtml')
								->toHtml() 
							?>
						<?php else: ?>
							<?php $html = $_ampHelper->convertHtmlForAmp($this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_tab->getValue())->toHtml()) ?>
						<?php endif ?>
						
						<?php 
							if (!trim($html)) {
								continue;
							}
							$alias = $_tab->getTabType().$_tab->getValue();
							$label = $_tab->getTitle();
						?>
						<section>
							<h3 class="title text-uppercase"><?php echo $label; ?></h3>
							
							<div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>">
								<?php /* @escapeNotVerified */ echo $html; ?>
							</div>
						</section>
					<?php endif ?>
				<?php else: ?>
					<?php 
						$html = $this->getChildHtml($_tab->getTabType());
						if (!trim($html)) {
							continue;
						}
						$label = $_tab->getTitle();
					?>
					<section>
						<h3 class="title text-uppercase"><?php echo $label; ?></h3>
						
						<div class="data item content">
							<?php /* @escapeNotVerified */ echo $this->getChildHtml($_tab->getTabType()); ?>
						</div>
					</section>
				<?php endif ?>
			<?php endforeach ?>
		</amp-accordion>
	</div>
<?php endif ?>