<?php 
$_product = $this->getLoadProduct($this->getProductId());
$_productImage = $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setProduct($_product)->setTemplate('MGS_Amp::Magento_Catalog/product/image_custom.phtml')->toHtml();
$_productName = $block->escapeHtml($_product->getName());
$_productUrl = $block->getProductUrl($_product);

?>
<?php $_configAmpHelper = $this->helper('MGS\Amp\Helper\Configurable'); ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="product-item-info">
	<a class="product photo product-item-photo" href="<?= $_productUrl ?>?amp=1" title="<?= $_productName ?>">
		<?= $_productImage ?>
		<?php echo $themeHelper->getProductLabel($_product) ?>
	</a>
	<div class="product details product-item-details">
		<strong class="product name product-item-name">
			<a class="product-item-link" href="<?= $_productUrl ?>?amp=1"><?= $_productName ?></a>
		</strong>
		
		<?= $block->getProductPrice($_product); ?>
		
		
		<div class="product actions product-item-actions">
			<?php if($_product->isSaleable() && (($_product->getTypeId()=='simple' && !$_product->getTypeInstance()->hasOptions($_product)) || ($_product->getTypeId()=='configurable'))): ?>
				<div class="product-add-form">
					<form custom-validation-reporting="show-all-on-submit" action-xhr="<?php /* @escapeNotVerified */ echo str_replace('http:', '',$block->getUrl('amp_api/cart/add')) ?>" method="post"
						  id="product_addtocart_form<?php echo $_product->getId() ?>"
						  on="submit-success:ampminicart.refresh,amptotalcart.refresh,lightboxMessage<?php echo $_product->getId() ?>">
						<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
						<?php echo $_configAmpHelper->getAmpJsonOption($_product, '') ?>

						<amp-lightbox id="lightboxMessage<?php echo $_product->getId() ?>" layout="nodisplay" class="product-alert">
							<div class="lightbox" role="button" tabindex="0" on="tap:lightboxMessage<?php echo $_product->getId() ?>.close">
								<div submit-success>
									<template type="amp-mustache">
										{{^error}}
										<div class="message success">
											{{success}}
										</div>
										{{/error}}
										{{^success}}
										<div class="message error">
											{{error}}
										</div>
										{{/success}}
										
									</template>
								</div>
							</div>
						</amp-lightbox>
						  
						<button class="button btn-cart action tocart" type="submit"><span><?= __('Add to Cart'); ?></span></button>
					</form>
				</div>
			<?php else: ?>
				<div class="actions-primary">
					<a href="<?= $_productUrl ?>" class="action tocart"><span><?= __('View Detail'); ?></span></a>
				</div>
			<?php endif ?>
		</div>
	</div>
</div>

