<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\AbstractProduct
*/
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You may also like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>


<?php if ($exist):?>
	<div class="items-block-<?= $class; ?> product-block">
		<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
		<h3><span class="items-block-heading heading-related-brand"><?php echo $title ?></span></h3>
		<amp-carousel class="product-carousel" height="400" width="375" layout="responsive" type="slides" autoplay delay="5000">
			<?php $i=0; foreach ($items as $_item): $i++ ?>
				<?php
					$_productName = $block->escapeHtml($_item->getName());
					$_productUrl = $block->getProductUrl($_item);

					$_productImage = $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setProduct($_item)->setTemplate('MGS_Amp::Magento_Catalog/product/image.phtml')->toHtml();
				?>
				<?php if($i % 2 == 1): ?>
				<div class="products list product-items">
				<?php endif ?>
				<div class="product-item">
					<div class="product-item-info">
						<a class="product photo product-item-photo" href="<?= $_productUrl ?>" title="<?= $_productName ?>">
							<?= $_productImage ?>
						</a>
						<div class="product details product-item-details">
							<strong class="product name product-item-name">
								<a class="product-item-link" href="<?= $_productUrl ?>"><?= $_productName ?></a>
							</strong>
							
							<?= $block->getProductPrice($_item); ?>
							
							<div class="product actions product-item-actions">
								<div class="actions-primary">
									<a href="<?= $_productUrl ?>" class="action tocart"><span><?= __('View Detail'); ?></span></a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php if($i % 2 == 0 || $i == count($items)): ?>
				</div>
				<?php endif ?>
			<?php endforeach; ?>
		</amp-carousel>
	</div>
<?php endif; ?>
