<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \MGS\PurchasedProduct\Block\RecentOrder
 */
?>
<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>


<?php $selector = 'alo-content-'. uniqid(); ?>
<div class= "<?php /* @escapeNotVerified */ echo $selector?> recentorder suggest-slider autoplay hidden-xs" data-autoplay="true" data-speed="50000">
	<div class="notify-slider-wrapper content-products"       
	>
		<?php
		$_productCollection = $block->getLoadedProductCollection();
		$_helper = $this->helper('Magento\Catalog\Helper\Output');
		$themeHelper = $this->helper('MGS\PurchasedProduct\Helper\Data');
		?>
		<?php 
			$speed = $themeHelper->getSpeed();
			$timeout = $themeHelper->getTimeout();
			$realSpeed = $speed + $timeout;
		?>
		<div class="mage-magictabs mc-<?php /* @escapeNotVerified */ echo $this->escapeHtml($this->getTypeFilter());?> activated">
		<?php if (!$_productCollection->count()): ?>
		    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
		<?php else: ?>
		    <?php
		        $viewMode = 'grid';
		        $image = 'category_page_grid';
		        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		    /**
		     * Position for actions regarding image size changing in vde if needed
		     */
		    $pos = $block->getPositioned();
		    ?>
		    <?php 
		        $showCart       = 1;
		        $showCompare    = 1;
		        $showWishlist   = 1;
		        $showReview     = 1;
			?>
			
		    <div class="notify-slider products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
				<?php $iterator = 1; ?>
				
		        <ul class="slider products list items product-items">
		            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
					<?php foreach ($_productCollection as $_product): ?>
					<?php $size = $themeHelper->getResizeImage(); ?>
						<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
						<?php $productImage = $_imagehelper->init($_product, $image)->resize($size[0], $size[1])->getUrl(); ?>
						<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
						<span class="x-close"><?= __('Close') ?></span>
		                <div class="product-item-info" data-container="product-grid">
		                    
		                    <?php // Product Image ?>
		                    <div class="images-container">
		                        <div class="product-hover">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<img src="<?php echo $productImage ?>" class="img-responsive">
									</a>
		                        </div>
		                    </div>
		                    <div class="product details product-item-details products-textlink clearfix">
		                        <?php
		                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
		                        ?>
		                        <h2 class="product-name product-item-name">
		                            <a class="product-item-link"
		                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
		                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
		                            </a>
		                        </h2>
		                        <?php 
		                        	$info = $this->getInfoPurchased($_product);
		                        	if($info) :
								 ?>
									<div class="someone-purchased"><?php echo $info['name'];?></div>
			                        <span class="time-purchased"><?php echo $this->getInfoTime($info['time'])?></span>
									<span class="address-purchased"><?php echo $info['address']?></span>
									<span class="purchase-text">purchased</span>
									<?php if($themeHelper->getConfig('purchasedProduct/general/enabled_quickview')): ?>
									<span class="hidden-sm hidden-xs quick-view"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></span>
									<?php endif; ?>
			                    <?php endif; ?>
		                    </div>
		                </div>
		                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
		            <?php endforeach; ?>
		        </ul>
		    </div>
		    <?php // echo $block->getToolbarHtml() ?>
		    <?php if (!$block->isRedirectToCartEnabled()) : ?>
		        <script type="text/x-magento-init">
		        {
		            "[data-role=tocart-form], .form.map.checkout": {
		                "catalogAddToCart": {}
		            }
		        }
		        </script>
		    <?php endif; ?>
		<?php endif; ?>
		</div>
	</div>
</div>
<script type="text/javascript">
	 require([
    'jquery',
    ], function ($) {
		$('.x-close').on('click', function(){
			$('.notify-slider').addClass('close');
		});
		var counter = 0;
		setInterval(function(){
			$('.notify-slider .slider .item').removeClass('actived');
			var c = counter % $('.notify-slider .slider .item').length;
			++counter;	
			setTimeout(function(){
				$('.notify-slider .slider .item').eq(c).addClass('actived');
			}, <?php echo $timeout?>);
		}, <?php echo $realSpeed?>);
	"use strict";
	});
</script>
