<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>

<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php if($themeHelper->getStoreConfig('mpanel/product_details/reviews_summary')): ?>
	<?php echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)?>
<?php endif ?>
