<?php $mpanelHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $themeSettings = $mpanelHelper->getThemeSettings(); ?>
<?php $subCategories = $themeSettings['catalog']['sub_categories'];?>

<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Category left navigation
 *
 * @var $block \Magento\Catalog\Block\Navigation
 */
?>
<?php if ($subCategories): ?>
	<?php if (!$block->getCategory()) {
		return;
	} ?>
	<?php $_categories = $block->getCurrentChildCategories(); ?>
	<?php $_count = is_array($_categories) ? count($_categories) : $_categories->count(); ?>
	<?php if ($_count): ?>
		<div class="sub-categories">
			<ol class="items">
				<?php foreach ($_categories as $_category): ?>
					<?php if ($_category->getIsActive()): ?>
						<li class="item">
							<a href="<?php /* @escapeNotVerified */ echo $block->getCategoryUrl($_category) ?>"<?php if ($block->isCategoryActive($_category)): ?> class="current"<?php endif; ?>><?php echo $block->escapeHtml($_category->getName()) ?></a>
							</li>
					<?php endif; ?>
				<?php endforeach ?>
			</ol>
		</div>
	<?php endif; ?>

<?php endif;?>
