<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Multishipping\Block\Checkout\Address\Select $block */
?>
<div class="multicheckout">
    <div class="block block-billing">
    <?php foreach ($block->getAddress() as $_address): ?>
        <div class="box box-billing-address">
            <div class="box-content">
                <address>
                    <?php if ($block->isAddressDefaultBilling($_address)): ?>
                        <strong class="color-theme"><?php /* @escapeNotVerified */ echo __('Default Billing') ?></strong><br />
                    <?php endif; ?>
                    <?php if ($block->isAddressDefaultShipping($_address)): ?>
                       <strong class="color-theme"><?php /* @escapeNotVerified */ echo __('Default Shipping') ?></strong> <br />
                    <?php endif; ?>
                    <?php echo $block->getAddressAsHtml($_address) ?>
                </address>
            </div>
            <div class="box-actions">
                <a href="<?php /* @escapeNotVerified */ echo $block->getEditAddressUrl($_address) ?>" class="btn btn-secondary btn-xs margin-right10 action edit"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
                <a href="<?php /* @escapeNotVerified */ echo $block->getSetAddressUrl($_address) ?>" class="btn btn-primary btn-xs action select"><span><?php /* @escapeNotVerified */ echo __('Select Address') ?></span></a>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
	<hr class="margin-top25 margin-bottom10">
    <div class="actions-toolbar">
		<div class="row">
			<div class="col-sm-4 col-xs-12 margin-top15">
				<a href="<?php /* @escapeNotVerified */ echo $block->getBackUrl() ?>" class="action btn btn-full btn-primary back"><span><?php /* @escapeNotVerified */ echo __('Back to Billing Information') ?></span></a>
			</div>
		</div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".actions": {
            "address": {
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddNewUrl() ?>"
            }
        }
    }
</script>
