<?php $_productCollection = $this->getDealsByCategories($this->getCategoryIds()) ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="content-block deal-product-cat-block <?php echo $this->getProductsCount(); ?>">
	
	<?php if (count($_productCollection)>0): ?>
		
		<?php 
			$blockId = rand() . time();
			$useSlider = $this->getUseSlider();
			$image = 'category_page_grid';
			$autoPlay = $this->getAutoplay() ? 'true' : 'false';
			$stopAuto = $this->getStopAuto() ? 'true' : 'false';
			$nav = $this->getNavigation() ? 'true' : 'false';
			$dot = $this->getPagination() ? 'true' : 'false';
		?>
		
		<div class="block widget mgs-products deal-products-one-item">
			<div class="items<?php if($useSlider): ?> owl-carousel<?php endif ?>" id="deal-products<?php echo $blockId; ?>">
			
				<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
				<?php $size = $themeHelper->getImageSize($this->getRatio()); ?>
				
				<?php $i=0; $j=0; foreach ($_productCollection as $_product): $i++; ?>
					
					<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl(); ?>
					<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
					
					<div class="border-banner">
						<div class="text text-center">
						
							<?php if($this->getData('mgs_panel_title') != ""): ?>
								<div class="playfair"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></div>
							<?php endif ?>
							<div class="deals-subtitle"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"><?php echo $_productNameStripped ?></a></div>
							
							<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
							<div class="deals-action">
								<a class="btn btn-default" href="<?php echo $_product->getProductUrl() ?>"><?php echo __('Shop Now'); ?></a>
							</div>
						</div>
						<div class="images">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>">
								<img class="img-responsive" src="<?php echo $productImage ?>" alt="<?php echo $_productNameStripped ?>">
							</a>
						</div>
					</div>
					
				<?php endforeach; ?>
				
			</div>
			
			<?php if($useSlider): ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function ($) {
						$('#deal-products<?php echo $blockId ?>').owlCarousel({
							items: 1,
							autoplay: <?php echo $autoPlay ?>,
							loop: <?php echo $autoPlay ?>,
							autoplayHoverPause: <?php echo $stopAuto ?>,
							nav: <?php echo $nav ?>,
							dots: <?php echo $dot ?>,
							navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
						});
					});
				</script>
			
			<?php endif ?>
		</div>	
	<?php else: ?>
		<?php if($this->getData('mgs_panel_title') != null || $this->getData('mgs_panel_note') != null): ?>
			<div class="content-heading">
				<?php if($this->getData('mgs_panel_title') != null): ?>
					<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
				<?php endif ?>
				<?php if($this->getData('mgs_panel_note') != null): ?>
					<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
				<?php endif ?>
			</div>
		<?php endif ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no deals matching the selection.') ?></div>
	<?php endif ?>
</div>