<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $exist = false ?>
<div class="edit-static-form">
	
	<div class="row">
		<div class="col-md-12 builder-title">
			<h2><?php echo __('Snapppt Shop Block') ?></h2>
		</div>
	</div>
	<form id="section-form" enctype="multipart/form-data" method="POST" action="<?php echo $this->getUrl('mpanel/element/save') ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
		<input type="hidden" name="page_id" value="<?php echo $this->getRequest()->getParam('page_id') ?>">
		<input id="block_type" type="hidden" name="type" value="snapppt">
		<input id="block_block_name" type="hidden" name="block_name" value="<?php echo $params['block'] ?>">
		<?php if(isset($params['id'])): ?>
			<?php 
				$child =  $this->getModel('MGS\Mpanel\Model\Childs')->load($params['id']);
				$exist = true;
				$settings = json_decode($child->getSetting(), true);
			?>
			<input type="hidden" name="child_id" value="<?php echo $params['id'] ?>">
		<?php endif ?>
		
		
		<div class="form-horizontal">
			<div id="form_tabs" class="tabbable">
				<ul class="nav nav-tabs">
					<li class="active">
						<a data-toggle="tab" href="#general"><?php echo __('General') ?></a>
					</li>
					
					<?php if($exist): ?>
						<li class="">
							<a id="code-tab-nav" data-toggle="tab" href="#code"><?php echo __('Embed Code') ?></a>
						</li>
					<?php endif ?>
				</ul>
				<div class="tab-content">
					<div id="general" class="tab-pane active">
						<div class="form-group">
							<label for="title" class="col-sm-4 control-label"><?php echo __('Title') ?></label>
							<div class="col-sm-8">
								<input type="text" id="title" class="input-text" name="setting[title]"<?php if($exist): ?> value="<?php echo htmlspecialchars($settings['title']) ?>"<?php endif ?> />
							</div>
						</div>
						
						<div class="form-group">
							<label for="col" class="col-sm-4 control-label"><?php echo __('Block col (12 to full)') ?></label>
							<div class="col-sm-8">
								<select id="col" class="required-entry input-text" name="col">
									<?php for($i=12; $i>=1; $i--): ?>
										<option value="<?php echo $i ?>"<?php if($exist && ($child->getCol()==$i)): ?> selected="selected"<?php endif ?>><?php echo $i ?></option>
									<?php endfor ?>
								</select>
							</div>
						</div>
						
						<div class="form-group">
							<label for="class" class="col-sm-4 control-label"><?php echo __('Custom Class') ?></label>
							<div class="col-sm-8">
								<input type="text" id="class" class="input-text" name="class"<?php if($exist): ?> value="<?php echo $child->getClass() ?>"<?php endif ?> />
							</div>
						</div>
						
						
						
						<div class="form-group">
							<label class="col-sm-4 control-label" for="additional_content"><?php echo __('Additional content') ?></label>
							<div class="col-sm-8">
								<textarea name="setting[additional_content]" id="content" class="input-text"><?php if($exist): ?><?php echo $settings['additional_content'] ?><?php endif ?></textarea>
							</div>
						</div>
						
						<div class="form-group">
							<label for="animation" class="col-sm-4 control-label"><?php echo __('Block Animation') ?></label>
							<div class="col-sm-4">
								<select onchange="changeAnimationClass(this.value)" id="animation" class="input-text" name="setting[animation]">
									<option value=""><?php echo __('Choose Animation Effect') ?></option>
									<?php foreach($helper->getAnimationEffect() as $animation=>$label): ?>
										<option value="<?php echo $animation ?>"<?php if($exist && ($settings['animation']==$animation)): ?> selected="selected"<?php endif ?>><?php echo $label ?></option>
									<?php endforeach ?>
								</select>
							</div>
							
							<div class="col-sm-4 text-center animated<?php if($exist && ($settings['animation']!='')): ?> <?php echo $settings['animation'] ?><?php endif ?>" id="animation-test">Animation Preview</div>
						</div>
						
						<div class="form-group">
							<label for="animation_delay" class="col-sm-4 control-label"><?php echo __('Animation Delay') ?></label>
							<div class="col-sm-8">
								<input type="text" placeholder="ms" id="animation_delay" class="input-text validate-number" name="setting[animation_delay]" <?php if($exist): ?> value="<?php echo $settings['animation_delay'] ?>"<?php endif ?>>
							</div>
						</div>
						
					</div>
				
					<?php if($exist): ?>
						<div id="code" class="tab-pane">
							<div class="form-group">
								<h4 class="col-sm-12"><?php echo __('For CMS:') ?></h4>
								<div class="col-sm-12">
									<pre><?php echo htmlspecialchars($child->getBlockContent()) ?></pre>
								</div>
							</div>
							
							<div class="form-group">
								<h4 class="col-sm-12"><?php echo __('For Layout Update XML:') ?></h4>
								<div class="col-sm-12">
									<pre><?php echo $helper->convertToLayoutUpdateXml($child) ?></pre>
								</div>
							</div>
						</div>
					<?php endif ?>
				</div>
			</div>
			<div class="row">
				<div class="form-group">
					<div class="col-md-12 builder-action">
						<div class="buttons">
							<?php if(!$exist): ?>
								<button type="button" class="btn btn-back" onclick="history.go(-1)"><span><span><?php echo __('Back') ?></span></span></button>
							<?php endif ?>
							<input type="submit" value="<?php echo __('Submit') ?>" class="btn btn-primary"/>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>

<script type="text/javascript">
	var currentAnimate = '';
	<?php if($exist): ?>
		currentAnimate = '<?php echo $settings['animation'] ?>';
	<?php endif ?>
	
	function changeAnimationClass(animate){
		require([
			'jquery',
		], function(jQuery){
			(function($) {
				if(currentAnimate!=''){
					$('#animation-test').removeClass(currentAnimate);
				}
				$('#animation-test').addClass(animate);
				currentAnimate = animate;
			})(jQuery);
		});
	}
	
</script>