<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" id="switcher-language">
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>">
			<label on="tap:storeviewlist.toggleVisibility" role="button" tabindex="0"><span><?= $block->escapeHtml($block->getStoreName()) ?></span></label>
        </div>
        <ul class="dropdown switcher-dropdown" id="storeviewlist" hidden>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
					<?php $dataUrl = $block->getTargetStorePostData($_lang) ?>
					<?php $dataUrl = json_decode($block->getTargetStorePostData($_lang), true) ?>
					<?php 
						$url = $dataUrl['action'];
						foreach($dataUrl['data'] as $key=>$value){
							$url .= $key.'/'.$value.'/';
						}
						$url .= '?amp=1';
					?>
					
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                        <a href="<?php echo $url ?>">
                            <?= $block->escapeHtml($_lang->getName()) ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
