<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="dropdown dropdown-switcher language switcher-currency" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
	<button class="switcher-toggle dropdown-toggle" type="button" data-toggle="dropdown"><?php /* @escapeNotVerified */ echo __('Currency') ?><i class="fa fa-angle-down" aria-hidden="true"></i></button>
	<ul class="dropdown-menu">
		<?php foreach ($currencies as $_code => $_name): ?>
			<?php if ($_code != $currentCurrencyCode): ?>
				<li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
					<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
				</li>
			<?php else: ?>
				<li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option switcher-active">
					<a href="javascript:void(0);"><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
				</li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
