<?php $helper = $this->helper('MGS\Mpanel\Helper\Data') ?>
<?php $canUsePanel = $helper->acceptToUsePanel() ?>
<?php $block = $this->getBlock() ?>
<div class="footer-container">
	<div class="middle-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_about_us')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_links_block2')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_newsletter')->setCanUsePanel($canUsePanel)->toHtml() ?>
				</div>
			</div>
		</div>
	</div>
	<div class="bottom-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				</div>
			</div>
		</div>
	</div>
</div>