<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>

<?php echo $this->getLayout()->createBlock("Magento\Contact\Block\ContactForm")->setTemplate("Magento_Contact::map.phtml")->toHtml();?>

<div class="contact-form-content">
	<h2 class="text-uppercase"><?php echo __('Write Your Review'); ?></h2>
	<form class="form contact"
	  action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
	  id="contact-form"
	  method="post"
	  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
	  data-mage-init='{"validation":{}}'>
		<div class="row">
			<div class="col-sm-6 col-xs-12">
				<div class="form-group name required">
					<label for="name"><?php echo __('Enter your name'); ?></label>
					<input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text form-control" type="text" data-validate="{required:true}"/>
				</div>
				<div class="form-group email required">
					<label for="email"><?php echo __('Enter your Email'); ?></label>
					<input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text form-control" type="email" data-validate="{required:true, 'validate-email':true}"/>
				</div>
				<div class="form-group telephone">
					<label for="telephone"><?php echo __('Enter your Number phone'); ?></label>
					<input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text form-control" type="text" />
				</div>
			</div>
			<div class="col-sm-6 col-xs-12">
				<div class="form-group comment required">
					<label for="comment"><?php echo __('What’s on your mind'); ?></label>
					<textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text form-control" cols="5" rows="3" data-validate="{required:true}"></textarea>
				</div>
			</div>
		</div>
		<div class="actions-toolbar">
			<input type="hidden" name="hideit" id="hideit" value="" />
			<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit btn btn-primary">
				<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
			</button>
		</div>
	</form>
</div>