<?php $_productCollection = $this->getSaleProductByCategories($this->getCategoryIds()) ?>
<?php $_collectionSize = $_productCollection->count() ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>
<div class="content-block new-products-block new-products-list-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	
	<?php if ($_collectionSize): ?>
		<?php $ratio = $this->getRatio(); ?>
		<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
		<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php $numberCol = $this->getNumbercol(); ?>
		<?php $numberOfCol = $this->getPercol(); ?>
		<?php $col = $themeHelper->convertPerRowtoCol($numberCol); ?>
		<?php $onRow = $numberCol * $numberOfCol; ?>
		<?php $blockId = rand() . time(); ?>
		<?php  ?>
		<?php  ?>
		<div class="block widget list-products mgs-sale-products sale-products-list <?php if($useSlider): ?>product-list-carousel<?php endif ?>">
			<div class="block-content row">
			
				<?php if($useSlider): ?>
				<div class="owl-carousel" id="sale-products-list-carousel-<?php echo $blockId; ?>">
				<?php endif ?>
				
					<?php $i=0; foreach($_productCollection as $_product): $i++; ?>
						<?php if($i % $numberOfCol == 1): ?>
							<div class="list-product-col <?php if(!$useSlider): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-12<?php endif ?>">
						<?php endif ?>
								<?php echo $this->getLayout()
												->createBlock('MGS\Mpanel\Block\Products\ProductItem')
												->setProductId($_product->getId())
												->setThemeHelper($themeHelper)
												->setImageHelper($_imagehelper)
												->setCatalogHelperOutput($_helper)
												->setRatio($ratio)
												->setUseSlider($useSlider)
												->setTemplate('MGS_Mpanel::products/list_items.phtml')
												->toHtml(); ?>
						<?php if($i % $numberOfCol == 0 || $i == count($_productCollection)): ?>
							</div>
						<?php endif ?>
						<?php // Clearfix ?>
							<?php if(!$useSlider && ($i % $onRow == 0)): ?>
								<div class="clearfix visible-lg visible-md"></div>
							<?php endif ?>
							
							<?php if(!$useSlider && ($i % (2 * $numberOfCol) == 0)): ?>
								<div class="clearfix visible-sm"></div>
							<?php endif ?>
						<?php // End Clearfix ?>
					<?php endforeach ?>
				
				<?php if($useSlider): ?>
				</div>
				<?php endif ?>
				
			</div>
		</div>
		<?php if($useSlider): ?>
			<?php $autoPlay = $this->getAutoplay() ? 'true' : 'false'; ?>
			<?php $stopAuto = $this->getStopAuto() ? 'true' : 'false'; ?>
			<?php $nav = $this->getNavigation() ? 'true' : 'false'; ?>
			<?php $dot = $this->getPagination() ? 'true' : 'false'; ?>
			<script type="text/javascript">
				require([
					'jquery',
					'mgs/owlcarousel'
				], function ($) {
					$('#sale-products-list-carousel-<?php echo $blockId; ?>').owlCarousel({
						items: <?php echo $numberCol ?>,
						autoplay: <?php echo $autoPlay ?>,
						autoplayHoverPause: <?php echo $stopAuto ?>,
						nav: <?php echo $nav ?>,
						dots: <?php echo $dot ?>,
						rtl: true,
						<?php if($lazyLoad): ?>lazyLoad: true,<?php endif ?>
						navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
						responsive:{
							0:{
								items:1
							},
							768:{
								items:2
							},
							992:{
								items:<?php echo $numberCol; ?>
							}
						}
					});
				});
			</script>
		<?php endif ?>
	<?php else: ?>
		<div role="alert" class="alert alert-warning"><?php echo __('There are no products matching the selection.') ?></div>
	<?php endif ?>
</div>