<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
//roy add
$sidebarBlock = $objectManager->get('\Magento\Checkout\Block\Cart\Sidebar');
?>
<!-- roy add start -->
<script type="text/javascript">
    window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($sidebarBlock->getConfig()); ?>;
</script>
<!-- roy add end -->
<script type="text/javascript">
    var QUICKVIEW_BASE_URL = '<?php echo $baseUrl; ?>';
</script>