<?php $collection = $block->getBrandCollection(); ?>
<?php $themeHelper = $this->helper('MGS\Amp\Helper\Setting'); ?>
<?php $helper = $this->helper('MGS\Brand\Helper\Data'); ?>

<div class="content-block brand-block brand-grid-block">
	<?php if($this->getData('mgs_panel_title') != "" || $this->getData('mgs_panel_note') != ""): ?>
		<div class="content-heading">
			<?php if($this->getData('mgs_panel_title')): ?>
				<h3 class="title"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_title')) ?></h3>
			<?php endif ?>
			<?php if($this->getData('mgs_panel_note')): ?>
				<div class="block-note"><?php echo $themeHelper->decodeHtmlTag($this->getData('mgs_panel_note')) ?></div>
			<?php endif ?>
		</div>
	<?php endif ?>
	<?php if (count($collection)>0): ?>
		<?php $useSlider = $this->getUseSlider(); ?>
		<?php if($useSlider): ?>
			<div class="clear-owl-carousel">
				<amp-carousel class="brand-carousel" height="170" layout="fixed-height" type="slides"<?php if($this->getAutoplay()): ?> autoplay delay="5000"<?php endif ?><?php if($this->getNavigation()):?> controls<?php endif ?>>
					<?php $width=$height=$i=0; foreach ($collection as $brand): $i++ ?>
						<?php $imageUrl = $brand->getSmallImageUrl()?>
						<?php 
							try{
								list($width, $height, $type, $attr) = getimagesize(str_replace('https://','http://',$imageUrl));
							}catch(Exception $e){}
						?>
						<?php if($i % 2 == 1): ?>
						<div class="products list product-items">
						<?php endif ?>
						<div class="product-item">
							<a href="<?php echo $brand->getUrl(); ?>" title="<?php echo $brand->getName() ?>">
								<amp-img width="<?= $width ?>" height="<?= $height ?>" layout="responsive" alt="<?php echo $brand->getName() ?>" src="<?= $imageUrl ?>"></amp-img>
							</a>
						</div>
						<?php if($i % 2 == 0 || $i == count($collection)): ?>
						</div>
						<?php endif ?>
					<?php endforeach; ?>
				</amp-carousel>
			</div>
		<?php else: ?>
		
			<div class="block widget mgs-brand">
				<div class="products list product-items">
					<?php $i=0; $j=0; foreach ($collection as $brand): $i++; ?>
						<?php $imageUrl = $brand->getSmallImageUrl()?>
						<?php list($width, $height, $type, $attr) = getimagesize(str_replace('https://','http://',$imageUrl)); ?>
						<div class="product-item">
							<a href="<?php echo $brand->getUrl(); ?>" title="<?php echo $brand->getName() ?>">
								<amp-img width="<?= $width ?>" height="<?= $height ?>" layout="responsive" alt="<?php echo $brand->getName() ?>" src="<?= $imageUrl ?>"></amp-img>
							</a>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		<?php endif ?>
	<?php else: ?>
	<?php endif ?>
</div>