<?php $canUsePanel = $this->getCanUsePanel() ?>
<?php $blocks = $this->getBlocks() ?>
<?php $blockName = $this->getBlockName() ?>
<?php if(count($blocks)>0): ?>
	<?php if($canUsePanel): ?>
		<div id="sort-block-<?php echo $blockName ?>" class="sort-block-container">
	<?php endif ?>
	<?php foreach($blocks as $_block): ?>
		<?php $setting = json_decode($_block->getSetting(), true) ?>
			<div class="panel-block-row <?php echo $this->getBlockClass($_block, $setting, $canUsePanel) ?>"<?php if(isset($setting['animation']) && $setting['animation']!=''): ?> data-appear-animation="<?php echo $setting['animation'] ?>"<?php endif ?><?php if(isset($setting['animation_delay']) && $setting['animation_delay']!=''): ?> data-appear-animation-delay="<?php echo $setting['animation_delay'] ?>"<?php endif ?> <?php if($canUsePanel): ?> id="block-<?php echo $_block->getId() ?>"<?php endif ?>>
				<?php if($canUsePanel): ?>
					<?php echo $this->getEditChildHtml($blockName, $_block) ?>
				<?php endif ?>
				<?php echo $this->getContentOfBlock($_block) ?>
			</div>
	<?php endforeach ?>
	<?php if($canUsePanel): ?>
		</div>
	<?php endif ?>
<?php endif ?>
<?php if($canUsePanel): ?>

	<div class="content-panel empty-block">
		<div class="add-new-block col-md-12">
			<a class="btn btn-primary popup-link btn-new-block" title="<?php echo __(' Add New Block'); ?>" onclick="return false" href="<?php echo $this->getUrl('mpanel/create/block',['name'=>$blockName, 'page_id'=>$this->getPageId()]) ?>">
				<em class="fa fa-plus"></em><?php echo __(' Add New Block'); ?>
			</a>
		</div>
	</div>
<?php endif ?>