<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>
<?php if (count($block->getStores())>1): ?>
	<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
	<div class="dropdown dropdown-switcher language switcher-language" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
		<?php foreach ($block->getStores() as $_lang): ?>
			<?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>
				<button class="switcher-toggle dropdown-toggle" type="button" data-toggle="dropdown">
					<?php echo $block->escapeHtml($_lang->getName()) ?>
					<i class="fa fa-angle-down" aria-hidden="true"></i>
				</button>
			<?php endif; ?>
		<?php endforeach; ?>
		<ul class="dropdown-menu">
			<?php foreach ($block->getStores() as $_lang): ?>
				<?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
					<li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
						<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
							<img alt="<?php echo $_lang->getCode(); ?>" src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/flags/' . $_lang->getCode() . '.png') ?>" /><?php echo $block->escapeHtml($_lang->getName()) ?>
						</a>
					</li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>
