<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="col-sm-6 col-xs-12">
	<div class="block block-customer-login">
		<div class="block-title">
			<h2 id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></h2>
		</div>
		<div class="block-content" aria-labelledby="block-customer-login-heading">
			<form class="form form-login"
				  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
				  method="post"
				  id="login-form"
				  data-mage-init='{"validation":{}}'>
				<?php echo $block->getBlockHtml('formkey'); ?>
				<fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
					<div class="form-group field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
					<div class="form-group field email required">
						<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
						<div class="control">
							<input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
						</div>
					</div>
					<div class="form-group field password required">
						<label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
						<div class="control">
							<input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="form-control input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
						</div>
					</div>
					<?php echo $block->getChildHtml('form_additional_info'); ?>
					<div class="actions-toolbar">
						<div class="form-group primary"><button type="submit" class="action login btn btn-primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button></div>
						<div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a></div>
					</div>
				</fieldset>
			</form>
		</div>
	</div>
</div>
