<?php $cssCategory = '
.category-view-amp {
	margin-bottom: 40px;
}
.category-view-amp .category-description {
	margin-top: 20px;
	border: 1px solid #eaeaea;
	text-align: center;
	padding: 15px;
	border-radius: 5px;
}
.category-view-amp .category-cms {
	margin-top: 20px;
}
.filter-count-label{display:none}
.filter-options .count::before{content: "(";}
.filter-options .count::after{content: ")";}
'; ?>
<?php
// *
// Pagination 
// *****
$_ampPagination = '';
$cssCategory .= $_ampPagination;
?>
<?php
// *
// Toolbar 
// *****
$_ampToolbar = '
.toolbar {
	display: -webkit-box;
	display: -ms-flexbox;
	display: flex;
	-webkit-box-align: center;
	-ms-flex-align: center;
	align-items: center;
	position: relative;
}
.toolbar .limiter {
	display:none
}

.toolbar .toolbar-sorter {
	border: 1px solid #eaeaea;
	border-radius: 30px;
	padding: 0 15px;
	white-space: nowrap;
	margin-left: auto;
}
.toolbar .toolbar-sorter .sorter-label {
	font-size: 12px;
	height:40px;
	line-height:40px
}

.toolbar .sorter-label {
	-webkit-appearance: none;
	-moz-appearance: none;
	border: none;
	background-color: transparent;
	padding: 0;
	height: 24px;
	color: #878787;
	font-size: 1rem;
	font-weight: 400;
	display: inline-block;
	vertical-align: top;
}
.toolbar .sorter-action:before {
	content: "\e942";
	font-family: "Pe-icon-7-stroke";
	font-size: 1rem;
	vertical-align: text-bottom;
	line-height: 1;
}
.toolbar .sorter-action.sort-desc:before {
	content: "\e688";
}
.toolbar .sorter-action span {
	border: 0;
	clip: rect(0, 0, 0, 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	width: 1px;
}
.toolbar .toolbar-amount,
.toolbar .modes {
	display: none;
}
.toolbar .sort-by-switcher{line-height:40px}
.toolbar .sort-by-switcher:before {
    content: "\e682";
    font-family: "Pe-icon-7-stroke";
    font-size: 20px;
    vertical-align: text-bottom;
    line-height: 1;
}
.toolbar .sort-by-switcher.sort-desc:before {
    content: "\e688";
}
.toolbar .sorter-position {
	position: absolute;
    z-index: 1;
    left: 0;
    right: 0;
    top: 100%;
    background: #fff;
    border: 1px solid #eaeaea;
    margin: 20px 0 0;
}
.toolbar .sorter-position .sort-product {
	display: block;
    padding: 10px 14px;
    border-bottom: 1px dotted #eaeaea;
}
';
$cssCategory .= $_ampToolbar;
?>
<?php
// *
// Top Toolbar 
// *****
$_ampTopToolbar = '
.catalog-top-toolbar {
	margin-bottom: 20px;
}
.catalog-top-toolbar .toolbar .limiter,
.catalog-top-toolbar .toolbar .pages {
	display: none;
}
.catalog-top-toolbar .action-filter {
	color: #222;
	font-size: 36px;
	background:none;
	border:none
}
.catalog-top-toolbar .action-filter span:before {
	content: "\e659";
	font-family: "Pe-icon-7-stroke";
}
';
$cssCategory .= $_ampTopToolbar;
?>
<?php
// *
// Bottom Toolbar 
// *****
$_ampBottomToolbar = '
.bottom-toolbar {
	margin-top: 30px;
}
.bottom-toolbar .action-filter,
.bottom-toolbar .filter-placeholder,
.bottom-toolbar .toolbar-sorter {
	display: none;
}
.pages {
    width: 100%;
    display: block;
    padding-top: 12px;
    border-top: 1px solid #ddd;
    margin: 0;
}
.pages .pagination {
    margin: 0 auto;
    display: table;
}
.pages .pagination .item {
    padding: 0 12px;
	float: left;
}
.pages .pagination .item a {
    text-align: center;
    line-height: 38px;
    color: #5b5b5b;
    display: block;
    padding: 0;
    border: none;
    background: none;
}
.pages .pagination .item.current a {
    color: #ec0101;
}
';
$cssCategory .= $_ampBottomToolbar;
?>

<?php
// *
// LayerNavigation
// *****
$_ampLayerNavigation = '
.block-content.filter-content{
	width:100%;
	padding:20px 15px;
}
amp-sidebar.block.filter {
	max-width: calc(100vw - 50px);
	left: 0;
	right: 0;
	height: 100vh;
	top: 0;
	bottom: 50px;
	background: #fff;
}
.block.filter .filter-title {
    display:none
}

.filter-options > li {
    margin: 0 0 50px;
}

.filter-options > li input[type="checkbox"] {
	display: none;
}
.filter-options-title {
	font-size: 18px;
    font-weight: 600;
    color: #222;
    margin-top: 0;
    margin-bottom: 25px;
	display: block;
	position:relative;
}
.filter-options-title:before {
	height: 2px;
	width: 60px;
	content: "";
	position: absolute;
	bottom: -3px;
	background-color:
	#222;
	left: 0;
}
.swatch-option-link-layered0,
.swatch-option-link-layered3 {
	display: inline-block;
}
.swatch-option-link-layered1,
.swatch-option-link-layered2 {
	margin-bottom: 10px;
}
a.swatch-option-link-layered {
	color: #999;
}
.swatch-option-link-layered1 span.swatch-option-link-layered,
.swatch-option-link-layered2 span.swatch-option-link-layered {
	color: #222;
}
.swatch-option-link-layered0 .swatch-option-link-layered,
.swatch-option-link-layered3 .swatch-option-link-layered {
	border: 1px solid #eaeaea;
    background-color: transparent;
    color: #bbb;
    font-size: 14px;
    line-height: 30px;
    min-width: 20px;
    border-radius: 0;
    padding: 0;
    width: 38px;
    height: 30px;
	display: block;
    text-align: center;
	border-radius: 2px;
}
.swatch-option-link-layered0 span.swatch-option-link-layered,
.swatch-option-link-layered3 span.swatch-option-link-layered {
	border-color: #222;
	color: #222;
}
.filter-options ul.items > .item {
    font-size: 15px;
    color: #222;
    display: block;
    padding-right: 20px;
    margin-bottom: 8px;
	padding-bottom:5px;
	border-bottom: 1px solid #f0f0f0;
}
.filter-options ul.items > .item > a {
	color: #8e8e8e;
}
.filter-options ul.items > .item > a .count {
	font-size: 14px;
	color: #b1b1b1;
	float:right;
}
.swatches-thumb {
	width: 20px;
	height: 20px;
	border-radius: 10px;
	background-size: cover;
	background-repeat: no-repeat;
	background-position: center;
	margin: 0 10px 0 0;
	display: inline-block;
}
.swatches-option--label {
	vertical-align: top;
	font-size: 14px;
}
.filter-current {
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    padding: 15px;
}
.filter-current .block-subtitle {
    -ms-flex: 0 0 100%;
    flex: 0 0 100%;
    max-width: 100%;
    display: block;
    color: #222;
    text-transform: uppercase;
    font-size: 1.25rem;
    margin: 0 0 10px;
}
.filter-current .shoppingby-item {
    margin-right: 20px;
}
.action.clear.filter-clear,
.filter-current .shoppingby-item .state-item {
    padding: 5px 8px;
    border: 1px solid #eaeaea;
    background: #fff;
    color: #222;
    border-radius: 2px;
    margin-bottom: 5px;
    font-size: .875rem;
    position: relative;
	display: block;
}
.filter-current .shoppingby-item .filter-label {
	font-weight: 600;
}
.filter-current .shoppingby-item .filter-label:after {
	content: ":";
}
.filter-current .shoppingby-item .action.remove:after {
	font-family: "Pe-icon-7-stroke";
    font-size: 16px;
    content: "\e681";
}
';
$cssCategory .= $_ampLayerNavigation;
?>

<?php /* Custom Style from backend for category pages */ ?>
<?php $helper = $this->helper('MGS\Amp\Helper\Config') ?>
<?php if($customStyle = $helper->getStoreConfig('mgs_amp/custom_style/category_style')): ?>
	<?php $cssCategory .= $customStyle; ?>
<?php endif ?>

<?= $cssCategory ?>


