<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar as Toolbar;
?>
<div class="toolbar-sorter sorter">
	<?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
		<?php if($block->isOrderCurrent($_key)): ?>
			<label on="tap:sorter_position.toggleVisibility" class="sorter-label" tabindex="0" role="button"><?= __('Sort by ') ?><span><?= $block->escapeHtml(__($_order)) ?></span></label>
		<?php endif; ?>
	<?php endforeach ?>
    <div id="sorter_position" class="sorter-position" hidden>
    	<?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
			<?php
				$direction = strtolower($block->getCurrentDirection());
				if ($block->isOrderCurrent($_key)) {
					$direction = $direction == 'asc' ? 'desc' : 'asc';
				}
	
				$params = array(
					Toolbar::ORDER_PARAM_NAME => $_key,
					Toolbar::DIRECTION_PARAM_NAME => $direction,
				);
	
				if ($block->getDefaultPerPageValue() !== $block->getLimit()) {
					$params[Toolbar::LIMIT_PARAM_NAME] = $block->getLimit();
				}
	
			?>
			<a class="sort-product <?php if($block->isOrderCurrent($_key)): ?> sorter-active<?php endif; ?>" href="<?= $block->getPagerUrl($params) ?>"><?= $block->escapeHtml(__($_order)) ?></a>
    	<?php endforeach; ?>
    </div>
	<a class="sort-by-switcher sort-desc" title="<?= __('Ascending') ?>" href="<?= $block->getPagerUrl(array(Toolbar::DIRECTION_PARAM_NAME => 'desc')) ?>" <?php if ($block->getCurrentDirection() == 'desc'): ?>hidden<?php endif; ?>></a>
	<a class="sort-by-switcher sort-asc" title="<?= __('Descending') ?>" href="<?= $block->getPagerUrl(array(Toolbar::DIRECTION_PARAM_NAME => 'asc')) ?>" <?php if ($block->getCurrentDirection() == 'asc'): ?> hidden<?php endif; ?>></a>
</div>
