<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_configAmpHelper = $this->helper('MGS\Amp\Helper\Configurable'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form">
    <form custom-validation-reporting="show-all-on-submit" action-xhr="<?php /* @escapeNotVerified */ echo str_replace('http:', '',$block->getUrl('amp_api/cart/add')) ?>" method="post"
          id="product_addtocart_form"
		  on="submit-success:ampminicart.refresh,amptotalcart.refresh,lightboxMessage<?php echo $_product->getId() ?>">
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <?php echo $block->getChildHtml('form_top'); ?>

		<?php echo str_replace('data-text','[text]',$_configAmpHelper->getAmpJsonOption($_product, $block->getChildHtml('amp_product_info_form_content'))) ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?= $block->getChildChildHtml('amp_options_container') ?>
        <?php endif;?>
        <?php //echo $block->getChildHtml('form_bottom'); ?>
		
		<?php if($_product->isSaleable() && (($_product->getTypeId()=='simple' && !$block->hasOptions()) || ($_product->getTypeId()=='grouped'))): ?>
			<?php echo $block->getChildHtml('amp_product_info_form_content') ?>
		<?php elseif($_product->getTypeId()!='configurable'): ?>
			<?php if($_product->isSaleable() && $_product->getTypeId()!='simple'): ?>
				<a href="<?php echo $_configAmpHelper->getCanonicalUrl() ?>" class="btn-cart"><?php echo __('Choose Option') ?></a>
			<?php endif ?>
		<?php endif ?>
    </form>
</div>