<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($block->isContentMode() || $block->isMixedMode()): ?>
	<?php $_configHelper = $this->helper('MGS\Amp\Helper\Config'); ?>
	<?php $_cmsLanding = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($this->getCurrentCategory()->getLandingPage())->toHtml(); ?>
    <div class="category-cms">
        <?= $_configHelper->convertHtmlForAmp($_cmsLanding); ?>
    </div>
<?php endif; ?>
