<?php $helper = $this->getHelper() ?>
<?php $pageLayout = $this->getPageLayoutConfig() ?>
<?php $perrow = $this->getPerrowConfig(); unset($perrow[0]) ?>
<form action="<?php echo $this->getUrl('mpanel/search/save') ?>" method="POST">
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><?php echo __('Layout') ?></span> 
				<select class="form-control input-sm" name="page_layout">
					<?php foreach($pageLayout as $layout): ?>
						<option value="<?php echo $layout['value'] ?>"<?php if($helper->getStoreConfig('mpanel/catalogsearch/layout')==$layout['value']): ?> selected="selected"<?php endif ?>><?php echo $layout['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><?php echo __('Per Row') ?></span> 
				<select class="form-control input-sm" name="per_row">
					<?php foreach($perrow as $row): ?>
						<option value="<?php echo $row['value'] ?>"<?php if($helper->getStoreConfig('mpanel/catalogsearch/product_per_row')==$row['value']): ?> selected="selected"<?php endif ?>><?php echo $row['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
		<button class="btn btn-default submit-top-panel" type="submit"><?php echo __('Submit') ?></button>
	</div>
</form>