<?php $helper = $this->getHelper() ?>
<?php $category = $helper->getCurrentCategory() ?>
<?php $pageLayout = $this->getPageLayoutConfig() ?>
<?php $perrow = $this->getPerrowConfig() ?>
<?php $ratios = $this->getRatioConfig() ?>
<form action="<?php echo $this->getUrl('mpanel/category/save') ?>" method="POST">
	<input type="hidden" name="id" value="<?php echo $category->getId() ?>"/>
	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><?php echo __('Layout') ?></span> 
				<select class="form-control input-sm" name="page_layout">
					<?php foreach($pageLayout as $layout): ?>
						<option value="<?php echo $layout['value'] ?>"<?php if($category->getPageLayout()==$layout['value']): ?> selected="selected"<?php endif ?>><?php echo $layout['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><?php echo __('Per Row') ?></span> 
				<select class="form-control input-sm" name="per_row">
					<?php foreach($perrow as $row): ?>
						<option value="<?php echo $row['value'] ?>"<?php if($category->getPerRow()==$row['value']): ?> selected="selected"<?php endif ?>><?php echo $row['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon"><?php echo __('Image Ratio') ?></span> 
				<select class="form-control input-sm" name="picture_ratio">
					<?php foreach($ratios as $ratio): ?>
						<option value="<?php echo $ratio['value'] ?>"<?php if($category->getPictureRatio()==$ratio['value']): ?> selected="selected"<?php endif ?>><?php echo $ratio['label'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</div>
	</div>
	
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
		<button class="btn btn-default submit-top-panel" type="submit"><?php echo __('Submit') ?></button>
	</div>
</form>