<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div id="search_block" class="block block-search">
    <div class="block block-title" role="button" tabindex="0" on="tap:searchLightbox"></div>
	<amp-lightbox id="searchLightbox" layout="nodisplay" class="search-lightbox">
		<div class="lightbox" role="button" tabindex="0">
			<button class="btn-close close-search" on="tap:searchLightbox.close"><span><?php echo __('Close Search') ?></span></button>
			<div class="block block-content">
				<form class="form minisearch" id="search_mini_form" action="<?= str_replace('http://', 'https://', $helper->getResultUrl()) ?>" method="get" target="_top">
					<div class="field search">
						<input id="search" type="text" name="<?= $helper->getQueryParamName() ?>" value="<?= $helper->getEscapedQueryText() ?>" placeholder="<?= __('Search for...'); ?>" class="input-text" maxlength="<?= $helper->getMaxQueryLength();?>" autocomplete="off"/>
					</div>
					<!--button type="submit" title="<?= $block->escapeHtml(__('Search')) ?>" class="action search"><span></span></button-->
				</form>
			</div>
		</div>
	</amp-lightbox>
    
</div>
