<?php $crumbs = $block->getCrumbs(); ?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<?php $mgsHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<div class="breadcrumbs">
    <div class="<?php if($mgsHelper->getStoreConfig('mpanel/breadcrumbs/fullwidth')): ?>container-fluid<?php else: ?>container<?php endif ?>">
		<ul class="items">
			<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
				<li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
				<?php if ($crumbInfo['link']) : ?>
					<a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
				<?php else: ?>
					<?= $block->escapeHtml($crumbInfo['label']) ?>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>