<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $cartAnimation = $themeHelper->getStoreConfig('ajaxcart/additional/animation_type'); ?>

<?php if($cartAnimation == 'flycart'): ?>
    <script type="text/x-magento-init">
    {
        "[data-block='footer_minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
<?php endif ?>