<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php if($themeHelper->getStoreConfig('mpanel/newsletter_popup/enable_newsletter')): ?>
	<?php  ?>
	<?php 
		$ObjectManagerMap = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $ObjectManagerMap->get('Magento\Store\Model\StoreManagerInterface');
		$currentStore = $storeManager->getStore();
		$currentUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
		$html = $themeHelper->getStoreConfig('mpanel/newsletter_popup/html_newsletter');
		$image = "";
		if($themeHelper->getStoreConfig('mpanel/newsletter_popup/newsletter_background')) {
			$image = $currentUrl.'bg_newsletter/'.$themeHelper->getStoreConfig('mpanel/newsletter_popup/newsletter_background');
		}
		
		$newsletterForm = $this->getLayout()->createBlock("Magento\Newsletter\Block\Subscribe")->setTemplate("Magento_Newsletter::subscribe_popup.phtml")->toHtml();
	?>
	<div style="display:none">
		<div id="newsletter-popup" <?php if($image): ?>style="background-image: url('<?php echo $image ?>');"<?php endif ?>>
			<div class="block-popup-subscribe">
				<div class="block-popup-top">
					<?php if($html): ?>
						<div class="newsletter-popup-content">
							<?php echo $html; ?>
						</div>
					<?php endif ?>
					<div class="newsletter-popup-form">
						<?php echo $newsletterForm; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		require(
			[
				'jquery',
				'Magento_Ui/js/modal/modal'
			],
			function(
				$,
				modal
			) {
				$(window).load(function () {
					if($(window).width() > 991) {
						if(getCookie('newsletterpopup')!='nevershow'){
							if ($('#newsletter-popup').length) {
								var options = {
									type: 'popup',
									modalClass: 'modal_newsletter-popup',
									responsive: true,
									innerScroll: true,
									title: '',
									buttons: []
								};

								var newsletterPopup = modal(options, $('#newsletter-popup'));

								$('#newsletter-popup').trigger('openModal');
							}
						}
					}
				});
				
				$('#newsletter-popup .checkbox input').click(function(){
					dontShowPopup('dont_show');
				});
				
				function getCookie(cname) {
					var name = cname + "=";
					var ca = document.cookie.split(';');
					for(var i=0; i<ca.length; i++) {
						var c = ca[i];
						while (c.charAt(0)==' ') c = c.substring(1);
						if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
					}
					return "";
				} 

				function dontShowPopup(el){
					if($('#'+el).prop('checked')) {
						var d = new Date();
						d.setTime(d.getTime() + (24*60*60*1000*365));
						var expires = "expires="+d.toUTCString();
						document.cookie = 'newsletterpopup' + "=" + 'nevershow' + "; " + expires;
					} else {
						document.cookie = 'newsletterpopup' + "= ''; -1";
					}
				}
			}
		);
	</script>
<?php endif ?>