<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<!doctype html>

<?php 
	$helper =  $this->getBuilderHelper();
	$url = $helper->getCssUrl();
	$canUsePanel = $helper->acceptToUsePanel();
?>

<html <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
		<?php echo $helper->getLinksFont() ?>
		<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $url ?>" /> 
		<?php if($helper->showButton()): ?>
		<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $helper->getPanelCssUrl() ?>" /> 
		<?php endif ?>
		<script>
			var WEB_URL = "<?php echo $helper->getUrlBuilder()->getUrl() ?>";
		</script>
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"}}' <?php /* @escapeNotVerified */ echo $bodyAttributes ?>>
		<?php if($helper->showButton() && !$helper->isPopup()): ?>
			<?php echo $topPanel ?>
		<?php endif ?>
		 <?php /* @escapeNotVerified */ echo $helper->convertContent($layoutContent, $builderContent) ?>
		
		<?php if($canUsePanel): ?>
			<script  type="text/javascript" src="<?php echo $this->getViewFileUrl('MGS_Mpanel::js/panel.js') ?>"></script>
		<?php endif ?>
    </body>
</html>
