<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<div class="form-password_forget col-sm-4 col-sm-offset-4">
    <div class="block-title t-a-c">
        <h2 class="title margin-bottom10" id="block-customer-login-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Recover password') ?></span></h2>
        <p class="margin-bottom30"><?php /* @escapeNotVerified */ echo __('Enter your email') ?></p>
    </div>
	<form class="form password forget"
		  action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
		  method="post"
		  id="form-validate"
		  data-mage-init='{"validation":{}}'>
		<fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
			<div class="form-group email required">
				<!--<label class="label"><?php /* @escapeNotVerified */ echo __('Enter your email'); ?></label>-->
				<div class="control">
					<input type="email" placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email...') ?>" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
				</div>
			</div>
			<?php echo $block->getChildHtml('form_additional_info'); ?>
		</fieldset>
		<div class="actions-toolbar margin-top10">
            <button type="submit" class="action submit forgotpassword-btn btn-primary"><span><?php /* @escapeNotVerified */ echo __('Recover') ?></span></button>
		</div>
        <div class="margin-top20 new-pwd-link">
            <p><?php /* @escapeNotVerified */ echo __('Remembered your password?') ?><a class="margin-left5 action remind" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Back to login') ?></span></a></p>
        </div>
	</form>
</div>
