<?php $galleryImages = $this->getGalleryImages(); ?>
<?php $zoom_image = $this->getEnableZoom(); ?>
<?php $lbox_image = $this->getLbox(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $arImage = $_product->getData('mgs_arimage') ?>
<?php $arTemplate = $this->getLayout()->createBlock("MGS\ClaueTheme\Block\AbstractProduct")->setProduct($_product)->setFullWidth(true)->setTemplate("MGS_ClaueTheme::arImage.phtml")->toHtml() ?>
<div id="owl-carousel-gallery" class="owl-carousel gallery-horizontal">
    <?php $i=0; foreach($galleryImages as $image): $i++ ?>
         
         <?php 
            $dataArrayImg =  $image->toArray();
            $productName = $this->getProduct()->getName();

            $lbImage = (isset($dataArrayImg['label']) &&  $dataArrayImg['label'] != null) ? $dataArrayImg['label'] : $productName;
        ?>
        <div class="product item-image<?php if($image->getDegreeImage()): ?> degree-container<?php elseif($image->getArImage()): ?><?php else: ?> imgzoom<?php endif ?><?php if($image->getArImage() && $arImage): ?> disable-owl-swipe<?php endif ?>" data-zoom="<?php echo $image->getImageZoom(); ?>">
            <?php if($image->getArImage()): ?>
                <?php if($arImage): ?>
                    <?php echo $arTemplate ?>
                <?php else: ?>
                    <img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
                <?php endif; ?>
            <?php else: ?>
                <?php if($lbox_image): ?>
                <?php if($image->getMediaType() != 'external-video'): ?>
                    <a class="lb" href="<?php echo $image->getsImageZoom(); ?>"><img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/></a>
                <?php else: ?>
                    <a class="lb video-link" href="<?php echo $image->getVideoUrl(); ?>"><img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/></a>
                <?php endif ?>
            <?php else: ?>
                <img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
                <?php if($image->getMediaType() == 'external-video'): ?>
                    <a target="_blank" class="popup-youtube btn btn-primary" href="<?php echo $image->getVideoUrl(); ?>"><?php echo __('Watch Video'); ?></a>
                <?php endif ?>
            <?php endif ?>
        <?php endif; ?>
			
			<?php if($image->getDegreeImage()): ?>
				<a id="degree_thumbnail" class="special-thumbnail degree-thumbnail" onclick="rotate360(<?php echo $i ?>)"><span></span></a>
                <?php elseif($image->getArImage()): ?>
                    <a class="ar-thumbnail" type="button"><span><i class="pe-7s-box2"></i></span></a>
				<?php endif ?>
        </div>
    <?php endforeach ?>
</div>
<script type="text/javascript">
    require([ 'jquery', 'mgs/owlcarousel' ], function ($) {
        $('#owl-carousel-gallery').owlCarousel({
            items: 4,
            autoplay: false,
            lazyLoad: false,
            nav: true,
            dots: false,
            mouseDrag: false,
            navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
            rtl: false,
			onInitialized: function(){
				var carowselHeight = $('#owl-carousel-gallery .owl-stage-outer').height();
				$('#owl-carousel-gallery .owl-item').height(carowselHeight);
			},
			<?php if($arImage): ?>
			touchDrag: false,
			<?php endif ?>
            responsive:{
                0:{
                    items:1
                },
                768:{
                    items:3
                },
                992:{
                    items:3
                },
                1200:{
                    items:4
                }
            }
        });
    });
    <?php if($zoom_image): ?>
        require([ 'jquery', 'zoom-images' ],function($) { 
            $(".imgzoom").each(function( index ) {
                zoomElement(this);
            });
        });
    <?php endif ?>
</script>
