<?php $galleryImages = $this->getGalleryImages(); ?>
<?php $zoom_image = $this->getEnableZoom(); ?>
<?php $lbox_image = $this->getLbox(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $arImage = $_product->getData('mgs_arimage') ?>
<div id="owl-carousel-gallery" class="owl-carousel gallery-horizontal">
    <?php foreach($galleryImages as $image): ?>
         <?php 
            $dataArrayImg =  $image->toArray();
            $productName = $this->getProduct()->getName();

            $lbImage = (isset($dataArrayImg['label']) &&  $dataArrayImg['label'] != null) ? $dataArrayImg['label'] : $productName;
        ?>
        <div class="product item-image<?php if($image->getDegreeImage()): ?> degree-container<?php elseif($image->getArImage()): ?><?php else: ?> imgzoom<?php endif ?><?php if($image->getArImage() && $arImage): ?> disable-owl-swipe<?php endif ?>" <?php if(!$image->getArImage()): ?>data-zoom="<?php echo $image->getImageZoom(); ?>" <?php endif; ?>>
            <?php if($image->getArImage()): ?>
                <?php if($arImage): ?>
                    <?php echo $this->getLayout()->createBlock("MGS\ClaueTheme\Block\AbstractProduct")->setProduct($_product)->setTemplate("MGS_ClaueTheme::arImage.phtml")->toHtml() ?>
                <?php else: ?>
                    <img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
                <?php endif; ?>
            <?php else: ?>
                <?php if($lbox_image): ?>
                    <?php if($image->getMediaType() != 'external-video'): ?>
                        <a class="lb" href="<?php echo $image->getImageZoom(); ?>"><img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/></a>
                    <?php else: ?>
                        <a class="lb video-link" href="<?php echo $image->getVideoUrl(); ?>"><img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/></a>
                    <?php endif ?>
                <?php else: ?>
                    <img class="img-responsive" src="<?php echo $image->getLargeImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
                    <?php if($image->getMediaType() == 'external-video'): ?>
                        <a target="_blank" class="popup-youtube btn btn-primary" href="<?php echo $image->getVideoUrl(); ?>"><?php echo __('Watch Video'); ?></a>
                    <?php endif ?>
                <?php endif ?>
            <?php endif; ?>
        </div>
    <?php endforeach ?>
</div>
<div class="horizontal-thumbnail-row">
    <div id="horizontal-thumbnail" class="owl-carousel horizontal-thumbnail">
        <?php $i = 0; foreach($galleryImages as $image): ?>
            <?php $lbImage = $image->getLabel() ? $image->getLabel() : $image->getLabelDefault(); ?>
            <div class="item-thumb<?php if($i == 0): ?> active<?php endif ?>" data-owl="<?php echo $i ?>" data-degree-thumbnail="<?php echo $image->getDegreeImage() ?>">
                <img class="img-responsive" src="<?php echo $image->getSmallImageUrl(); ?>" alt="<?php echo $lbImage ?>"/>
                <?php if($image->getMediaType() == 'external-video'): ?>
                    <a target="_blank" class="popup-youtube" href="<?php echo $image->getVideoUrl(); ?>"></a>
                <?php elseif($image->getDegreeImage()): ?>
					<a class="degree-thumbnail"><span></span></a>
                <?php elseif($image->getArImage()): ?>
                    <a class="ar-thumbnail"><span><i class="pe-7s-box2"></i></span></a>
				<?php endif ?>
            </div>
            <?php $i++; ?>
        <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">
    require([ 'jquery', 'mgs/owlcarousel' ], function ($) {
        $('#owl-carousel-gallery').owlCarousel({
            items: 1,
            autoplay: false,
            lazyLoad: false,
            nav: true,
            dots: false,
            mouseDrag: false,
            navText: ["<i class='pe-7s-angle-left'></i>","<i class='pe-7s-angle-right'></i>"],
            rtl: false,
			<?php if($arImage): ?>
			touchDrag: false,
			<?php endif ?>
			onInitialized: function(){
				var carowselHeight = $('#owl-carousel-gallery .owl-stage-outer').height();
				$('#owl-carousel-gallery .owl-item').height(carowselHeight);
			}
        });
        
        $('#owl-carousel-gallery').on('changed.owl.carousel', function(event) {
            var index = event.item.index;
            $('#horizontal-thumbnail .item-thumb').removeClass('active');
            $('#horizontal-thumbnail .item-thumb[data-owl='+index+']').addClass('active');
            $('#horizontal-thumbnail').trigger('to.owl.carousel', index);
			var degreeValue = $('#horizontal-thumbnail .item-thumb[data-owl='+index+']').attr('data-degree-thumbnail');
			if(degreeValue==1){
				var galleryHeight = $('#owl-carousel-gallery .owl-item').eq(index).parent().height();
				$('#owl-carousel-gallery .owl-item').eq(index).height(galleryHeight);
				rotate360(index);
			}
        });
        
        $('#horizontal-thumbnail').owlCarousel({
            items: 4,
            autoplay: false,
            lazyLoad: false,
            nav: true,
            dots: false,
            rtl: false,
            navText: ["<span class='fa fa-angle-left'></span>","<span class='fa fa-angle-right'></span>"],
            responsive:{
                0:{
                    items:2
                },
                480:{
                    items:2
                },
                768:{
                    items:3
                },
                992:{
                    items:4
                }
            }
        });
        
        $('#horizontal-thumbnail .item-thumb').click(function(){
            $('#horizontal-thumbnail .item-thumb').removeClass('active');
            var position = $(this).attr('data-owl');
            $('#owl-carousel-gallery').trigger('to.owl.carousel', position);
            $(this).addClass('active');
        });
    });
    <?php if($zoom_image): ?>
        require([ 'jquery', 'zoom-images' ],function($) { 
            $(".imgzoom").each(function( index ) {
                zoomElement(this);
            });
        });
    <?php endif ?>
</script>
