<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_configHelper = $this->helper('MGS\Amp\Helper\Config'); ?>
<p class="newsletter-note"><?= $_configHelper->getStoreConfig('mgs_amp/footer/newsletter_text') ?></p>
<form class="form subscribe newsletter"	action-xhr="<?= str_replace('http://', 'https://', $this->getUrl('amp_api/newsletter/new')) ?>"	method="post" id="newsletter_validate_detail">
	<div submit-success>
		<template type="amp-mustache">
			{{#success}}
				<div class="success-message">{{success}}</div>
			{{/success}}
			{{#error}}
				<div class="error-message">{{error}}</div>
			{{/error}}
		</template>
	  </div>
	  <div submit-error>
		<template type="amp-mustache">
			<div class="error-message"><?php echo __('Something went wrong with the subscription.') ?></div>
		</template>
	  </div>
	<div class="form-input">
		<input name="email" type="email" id="newsletter" required placeholder="<?= __('Your email address') ?>"/>
		<button on="tap:newsletter_validate_detail.submit" class="action subscribe primary user-valid valid"><?php echo __('Subscribe') ?></button>
	</div>
	
	
</form>
