<?php $helper = $this->getHelper() ?>
<?php $params = $this->getParams() ?>
<?php $block = $helper->getCmsBlockByIdentifier($params['id']) ?>
<?php $content = $block->getContent() ?>
<div class="edit-static-form">
	
	<div class="row">
		<div class="col-md-12 builder-title">
			<h2><?php echo __('Edit Static Block "%1"', $block->getTitle()) ?></h2>
		</div>
	</div>
	<form id="section-form" enctype="multipart/form-data" method="POST" action="<?php echo $this->getUrl('mpanel/post/staticblock') ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
		<input type="hidden" name="block_id" value="<?php echo $block->getId() ?>"/>
		<div class="form-horizontal">
			<div id="form_tabs" class="tabbable">
				<ul class="nav nav-tabs">
					<li class="active">
						<a id="additional-tab-nav" data-toggle="tab" href="#additional"><?php echo __('Content') ?></a>
					</li>
					
					<li class="">
						<a data-toggle="tab" href="#images"><?php echo __('Images') ?></a>
					</li>
				</ul>
				<div class="tab-content">
					
					<div id="additional" class="tab-pane active">
						<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Panel\Create\StaticContent')->setContent($content)->setTemplate('panel/create/element/static/content.phtml')->toHtml() ?>
					</div>
					
					<div id="images" class="tab-pane">
						<?php $images = $helper->getPanelUploadImages('panel') ?>
						
							<table class="table table-bordered images-table">
								<thead>
									<tr>
										<th class="td-image"><?php echo __('Image') ?></th>
										<th class="td-code"><?php echo __('Code') ?></th>
										<th class="td-remove"><?php echo __('Remove') ?></th>
									</tr>
								</thead>
							</table>
							<div class="panel-image-list">
								<table class="table table-bordered" id="panel-images">
									<tbody id="list-images">
									<?php if(count($images)>0): ?>
										<?php foreach($images as $_image): ?>
											<tr>
												<td class="a-center td-image">
													<img src="<?php echo $this->getPanelUploadSrc('panel',$_image) ?>" alt=""/>
												</td>
												<td class="td-code">
													<pre><?php echo $helper->convertImageWidgetCode('panel',$_image) ?></pre>
												</td>
												<td>
													<input type="checkbox" name="remove[]" value="<?php echo $_image ?>"/>
												</td>
											</tr>
										<?php endforeach ?>
									<?php endif ?>
									</tbody>
								</table>
							</div>
							
							<table class="table table-bordered" id="image-foot"<?php if(count($images)==0): ?> style="display:none"<?php endif ?>>
								<tfoot>
									<tr><td colspan="3"><?php echo __('If you want to insert image to content, please copy code and paste to content in HTML mode.') ?></td></tr>
								</tfoot>
							</table>
								
						
						
						<div id="upload-container">
							<div id="list-upload"></div>
							<button class="btn btn-default" onclick="newImageUpload()" type="button"><span class="fa fa-plus"></span> <?php echo __('Upload new Image') ?></button>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group">
					<div class="col-md-12 builder-action">
						<div class="buttons">
							<input type="submit" value="<?php echo __('Submit') ?>" class="btn btn-primary"/>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
</div>
<script type="text/javascript">

	
	function newImageUpload(){
		require([
			'jquery',
		], function(jQuery){
			(function($) {
				if($('#file_upload').length){
					if($('#upload_button').length){
						alert('<?php echo __('Please upload selected image first.') ?>');
					}else{
						alert('<?php echo __('Please choose file to upload.') ?>');
					}
				}else{
					html = '<div class="form-group"><div class="col-sm-4 choose-file-upload"><input id="file_upload" name="file_upload" type="file" onchange="chooseFileAction(this.id)"><span class="choose-label"><span class="fa fa-folder-o"> </span> &nbsp;<?php echo __('Choose File to Upload') ?></span></div><div class="col-sm-4" id="upload_action"></div></div>';
					$('#list-upload').html(html);
				}
				
			})(jQuery);
		});
	}
	
	function chooseFileAction(elId){
		require([
			'jquery',
		], function(jQuery){
			(function($) {
				fileName = $('#'+elId).val();
				arrName = fileName.split(".");
				extensionName = arrName[arrName.length - 1];
				extensionName = extensionName.toLowerCase();
				if((extensionName=='jpg') || (extensionName=='jpeg') || (extensionName=='png') || (extensionName=='gif')){
					html = fileName + ' <button type="button" class="btn btn-default" id="upload_button" onclick="uploadImage()"><img src="<?php echo $this->getViewFileUrl('MGS_Mpanel::images/small-ajax-loader.gif') ?>" id="upload-loading" style="display:none"/> <span class="fa fa-upload" id="upload-icon"></span> <?php echo __('Upload') ?></button>';
					$('#upload_action').html(html);
				}
			})(jQuery);
		});
	}
	
	function uploadImage(){
		require([
			'jquery',
		], function(jQuery){
			(function($) {
				if($('.alert-image-success').length){
					$('.alert-image-success').remove();
				}
				$('#upload-loading').show();
				$('#upload-icon').hide();
				var formData = new FormData();
				formData.append('file', $('#file_upload')[0].files[0]);
				$.ajax({
					url: "<?php echo $this->getUrl('mpanel/post/upload', ['type'=>'panel']) ?>",
					type: "POST",
					data: formData,
					contentType: false,
					cache: false,
					processData:false,
					success: function(data){
						var result = jQuery.parseJSON(data);
						if(result.result=='success'){
							html = '<tr ><td class="a-center td-image"><img src="<?php echo $this->getPanelUploadFolder('panel') ?>'+result.data+'" alt=""></td><td class="td-code"><pre>&lt;img src="{{media url="wysiwyg/panel/'+result.data+'"}}" alt=""/&gt;</pre><div class="alert alert-success alert-image-success"><?php echo __('The image was successfully uploaded.') ?></div></td><td><input name="remove[]" value="'+result.data+'" type="checkbox"></td></tr>';
							$('#list-images').append(html);
							$(".panel-image-list").animate({ scrollTop: $('#list-images').height()}, 300);
							$('#image-foot').show();
						}else{
							alert(result.data);
						}
						
						$('#list-upload').html('');
					}
				});
			})(jQuery);
		});
	}
</script>